### ISSUE TITLE
CSS user-select

### ISSUE THREAD

**Issue by ythy** [ythy/blog#224]
> The `user-select` CSS property controls whether the user can select text. This doesn't have any effect on content loaded as chrome, except in textboxes.

`user-select: none;` 
The text of the element and its sub-elements is not selectable. Note that the Selection object can contain these elements.

Example:
```html
<p>You should be able to select this text.</p>
<p class="unselectable">Hey, you can't select this text!</p>
```

```css
.unselectable {
  -moz-user-select: none;
  -webkit-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```

### 结论
AG-Grid 应用此属性使得表格内的元素无法被选择！
