### ISSUE TITLE
Display : Flex 居中

### ISSUE THREAD

**Issue by ythy** [ythy/blog#249]
容器display属性设置为flex后，可以针对横向和纵向轴设置居中。
![](https://mdn.mozillademos.org/files/15627/align1.png)

如上图所示, 当flex-redirection为row时， `justify-content`属性设置横向对齐， `align-items`设置纵向对齐方式。下面样式的效果即为div完全居中
```css
.box {
  display: flex;
  align-items: center;
  justify-content: center;
}

.box div {
  width: 100px;
  height: 100px;
}
```
