### ISSUE TITLE
MongoDB Deploy New Replica Set 

### ISSUE THREAD

**Issue by ythy** [ythy/blog#31]
###  prepare three instances 
config file : 
```
systemLog:
   destination: file
   path: E:\mongodb\logs\mongo.log
storage:
   dbPath: E:\mongodb\data\db_s1
net:
   bindIp: 192.10.9.1,127.0.0.1
   port: 27017
security:
   authorization: enabled
   keyFile: E:\mongodb\ssl.key
replication:
   replSetName: chat
```
### start mongod instances 
```
mongod --config E:\mongodb\config\chat1.conf
mongod --config E:\mongodb\config\chat2.conf
mongod --config E:\mongodb\config\chat3.conf
```
### Connect to one of mongod  instances 
``
mongo --port 27017
``
### initiate the replica set
`rs.initiate()` triggers an election and elects one of the members to be the primary.
```
rsconf = {
  _id: "chat",
  members: [
    {
     _id: 0,
     host: "192.10.9.1:27017"
    },
    {
     _id: 1,
     host: "192.10.9.1:27018"
    },
    {
     _id: 2,
     host: "192.10.9.1:27019"
    }
   ]
}

rs.initiate( rsconf )
```

### Create the user administrator
* Add a user using the `db.createUser()` method. The user should have at minimum the userAdminAnyDatabase role on the admin database.
* You must be connected to the **primary** to create users.
```
db.createUser(
  {
    user: "tom",
    pwd: "12345",
    roles: [ 
      { role: "readWriteAnyDatabase", db: "admin" },
      { role: "userAdminAnyDatabase", db: "admin" },
      { role: "dbAdminAnyDatabase", db : "admin"  },
      { role: "clusterAdmin", db : "admin"  },
     ]
  }
)

```
###  conclustions
* `keyFile` 必须与否不确定， 可以通过网络在线生成， 不能超过1024个字节
* 要新生成数据库，用已有的已经有用户验证的数据库，总出错
