### ISSUE TITLE
ag-grid ver.21 文字不可选控制

### ISSUE THREAD

**Issue by ythy** [ythy/blog#341]
```js
const GRID_PANEL_NORMAL_TEMPLATE =
 `<div class="ag-root ag-unselectable" role="grid" unselectable="on">
<ag-header-root ref="headerRoot" unselectable="on"></ag-header-root>
<div class="ag-floating-top" ref="eTop" role="presentation" unselectable="on">
```

```css
 .ag-unselectable {
    user-select: none !important; // disable user mouse selection
 }
```

通过这个`ag-unselectable`样式来控制的， 每个版本的控制方式或有差异
