### ISSUE TITLE
SCSS:  parent selector:

### ISSUE THREAD

**Issue by ythy** [ythy/blog#400]
[parent-selector](https://sass-lang.com/documentation/style-rules/parent-selector)

The parent selector, `&`, is a special selector invented by Sass that’s used in `nested selectors` to refer to the outer selector. It makes it possible to re-use the outer selector in more complex ways, like adding a pseudo-class or adding a selector before the parent.

```scss
.alert {
  // The parent selector can be used to add pseudo-classes to the outer
  // selector.
  &:hover {
    font-weight: bold;
  }

  // It can also be used to style the outer selector in a certain context, such
  // as a body set to use a right-to-left language.
  [dir=rtl] & {
    margin-left: 0;
    margin-right: 10px;
  }

  // You can even use it as an argument to pseudo-class selectors.
  :not(&) {
    opacity: 0.8;
  }
}
```
convert to 
```css
.alert:hover {
  font-weight: bold;
}
[dir=rtl] .alert {
  margin-left: 0;
  margin-right: 10px;
}
:not(.alert) {
  opacity: 0.8;
}
```

Conclusion: `&` refer parent class name.
