### ISSUE TITLE
谷歌内核64/70 BUG

### ISSUE THREAD

**Issue by ythy** [ythy/blog#439]
```html
<!DOCTYPE html>
<html>
 <head>
 <meta charset="utf-8" />
 <style type="text/css">
   
  html, body{
    height: 100%;
  }

  .wrapper{
    display: flex;
    flex-direction: column;
    height: 100%;
  }


  .grid{
    height: auto;
    display: flex;
    flex-direction: column;
    flex: 1 0 auto;
  }

 
  .keypoint{
    height: 100%;
    box-sizing: border-box;
    border: 1px red solid;
  }

 </style>
 </head>

<body>
  <div class="wrapper">
    <div class="grid">
       <div class="keypoint">
          i`m bad
       </div>
    </div> 
  </div>
</body>

</html>
```

以上例子，`keypoint` 容器，应当`100%`填充满, 但由于父容器高度是`auto`, 尽管父容器通过`flex`属性进行了100%填充，但是`keypoint`容器不能填充父容器！

`grid` 样式应当如下写法：
```css
  .grid{
    height: 0px;
    display: flex;
    flex-direction: column;
    flex: 1 0 auto;
  }
```
