### ISSUE TITLE
Element 焦点问题

### ISSUE THREAD

**Issue by ythy** [ythy/blog#481]
参考 https://html.spec.whatwg.org/multipage/interaction.html#focusable-area
`Focusable area` 描述重点： **the element's [tabindex value](https://html.spec.whatwg.org/multipage/interaction.html#tabindex-value) is non-null**, or the element is determined by the user agent to be focusable;

实践中设置2步让Div成为焦点区域
1. `div.setAttribute('tabIndex', 10)`,   让其具有`tabIndxe`属性
2. `div.classList?.add('focus-visible-none');  去掉焦点外框加粗样式
```css
.focus-visible-none:focus-visible{
  outline: 0px;
}
```
