### ISSUE TITLE
HTML 自适应初步

### ISSUE THREAD

**Issue by ythy** [ythy/blog#517]
## 范例一：

```css
@media screen and (max-width:1440px){
.textblock [data-font-size-pc='60']{font-size:4.16666667vw}
.textblock [data-font-size-pc='48']{font-size:3.33333333vw}
.textblock [data-font-size-pc='38']{font-size:2.63888889vw}
.textblock [data-font-size-pc='32']{font-size:2.22222222vw}
.textblock [data-font-size-pc='28']{font-size:1.94444444vw}
.textblock [data-font-size-pc='24']{font-size:1.66666667vw}
.textblock [data-font-size-pc='22']{font-size:1.52777778vw}
.textblock [data-font-size-pc='18']{font-size:1.25vw;}
.textblock [data-font-size-pc='14']{font-size:.97222222vw}
}
@media only screen and (max-width:767px){
.textblock [data-font-size-mo='36']{font-size:10vw}
.textblock [data-font-size-mo='30']{font-size:8.33333333vw}
.textblock [data-font-size-mo='26']{font-size:7.22222222vw}
.textblock [data-font-size-mo='22']{font-size:6.11111111vw}
.textblock [data-font-size-mo='18']{font-size:5vw}
.textblock [data-font-size-mo='16']{font-size:4.44444444vw}
.textblock [data-font-size-mo='14']{font-size:3.88888889vw}
.textblock [data-font-size-mo='12']{font-size:3.33333333vw}
}
```
标签设2种样式，对应PC或者MO
```html
<p data-font-size-pc="18" data-font-size-mo="14"></p>
```
