### ISSUE TITLE
REM HTML自适应  @media和 html.clientWidth 不匹配

### ISSUE THREAD

**Issue by ythy** [ythy/blog#518]
`@media only screen and (max-width:480px )` 中 `max-width:480px` 包含滚动条宽度
`html.clientWidth` 不包含滚动条宽度

1. 因此适配宽度时，首先全局固定滚动条宽度，下例为`10px`
```css
::-webkit-scrollbar {width: 10px;height: 10px;z-index: 30;position: relative;}
::-webkit-scrollbar-thumb {background: #aaa; -webkit-box-shadow: inset 0 0 6px #ccc;}
::-webkit-scrollbar-thumb:window-inactive {background: #aaa;}
```
2. 给`html`设定`font-size`时， PC端做相应的处理,  因为手机端滚动条不单独占位 
```js
        var docEl = document.documentElement,
        resizeEvt = 'orientationchange' in window ? 'orientationchange' : 'resize',
        recalc = function () {
            var clientWidth = docEl.clientWidth;
            if (!clientWidth) return;
             if(!("ontouchstart" in document.documentElement)){
                clientWidth += 10; // 此处判断如果PC端 加10像素
             }
            if(clientWidth>=960){
                 docEl.style.fontSize = 100 * (clientWidth / 1920) + 'px';
            }else if(clientWidth < 960 && clientWidth > 640){
                 docEl.style.fontSize = 100 * (clientWidth / 1600) + 'px';
            }else{
            	 docEl.style.fontSize = 100 * (clientWidth / 750) + 'px';
            }
        };
    window.addEventListener(resizeEvt, recalc, false);
    recalc();


```
