### ISSUE TITLE
table > td  内容居中方式

### ISSUE THREAD

**Issue by ythy** [ythy/blog#523]
默认是可以居中的，但是在chrome中，`form`标签默认样式如下：

```css
form {
    display: block;
    margin-top: 0em;
    margin-block-end: 1em;
}
```

这里有一个默认的底部的边距，如果需要上下居中的话，这个样式要通过`margin: auto`来去掉

**The End.**
