### ISSUE TITLE
Html  设置DIV高度=宽度

### ISSUE THREAD

**Issue by ythy** [ythy/blog#73]
```css
.imgbox {
    position: relative;
    width: 100%;        /* desired width */
}

.imgbox:before {
    content: "";
    display: block;
    padding-top: 100%;     /* before 对应的是imgbox的左边 100%就是imgbox的宽度；padding-top 100%就是将imgbox的高度按宽度展开 */
}
```
